apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-service
spec:
  selector:
    app: rabbitmq
  ports:
  - name: management-port
    port: 15672
    targetPort: 15672
  - name: rabbitmq-port
    port: 5672
    targetPort: 5672
  type: LoadBalancer