apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-sql-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-sql-server
  template:
    metadata:
      labels:
        app: ms-sql-server
    spec:
      containers:
      - name: ms-sql-server
        image: mcr.microsoft.com/mssql/server:2019-latest
        env:
        - name: ACCEPT_EULA
          value: "Y"
        - name: MSSQL_SA_PASSWORD
          value: "Qwerty12345"
        - name: MYSQL_PID
          value: Express
        ports:
        - containerPort: 1433
        volumeMounts:
        - name: sql-data
          mountPath: /var/opt/mssql
      volumes:
      - name: sql-data
        persistentVolumeClaim:
          claimName: ms-sql-server-pvc
